### ISSUE TITLE
sticky:after Unnecessary

### ISSUE THREAD

**Issue by leepeterson** [dvlopes/underskeleton#4]
The drop shadow in /sass/theme/_posts.scss#L7-L20 is unnecessary. Nothing else in the theme uses a light source, and this particular style of drop shadow died years ago. 

Use a subtle shadow, hard shadow or layered shadow, if anything, but it is preferred not to use such an opinionated design element in an otherwise flat theme design.

**Comment by diegoversiani** [comment]
@leepeterson I've replaced the shadow with a bottom border.
